"""create initial tables

Revision ID: f5438cc12727
Revises: 
Create Date: 2026-10-01 17:54:27.133916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5438cc12727'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_project_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=255), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=True),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_project_id', 'assets', ['asset_project_id'], unique=False)
    op.create_index('ix_assets_project_id_name', 'assets', ['asset_project_id', 'asset_name'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_project_id', sa.UUID(), nullable=False),
    sa.Column('chunk_asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['chunk_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_asset_id', 'chunks', ['chunk_asset_id'], unique=False)
    op.create_index('ix_chunks_project_id', 'chunks', ['chunk_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_project_id', table_name='chunks')
    op.drop_index('ix_chunks_asset_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_assets_project_id_name', table_name='assets')
    op.drop_index('ix_assets_project_id', table_name='assets')
    op.drop_table('assets')
    op.drop_table('projects')
    # ### end Alembic commands ###
