[project]
name = "mini-rag-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.15"
dependencies = [
    "aiofiles>=25.1.0",
    "dotenv>=0.9.9",
    "fastapi>=0.139.2",
    "langchain-community>=0.4.2",
    "langchain-core>=1.5.0",
    "langchain-text-splitters>=1.1.2",
    "motor>=3.7.1",
    "pydantic-settings>=2.14.2",
    "python-multipart>=0.0.32",
    "uvicorn>=0.51.0",
]
